version: "3"

services:
  app:
    build:
      context: ./
      args:
        HOST_UID: $HOST_UID
        HOST_GID: $HOST_GID
        TZ: $TZ
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: ./
        target: /home/jovyan/app
